### ISSUE TITLE
Limitation of 1024 pixels?

### ISSUE THREAD

**Issue by NickBolles** [bbx10/node-opc-server#1]
Where does the limitation of 1024 pixels come from? Can this be avoided?

**Comment by bbx10** [comment]
The limit can be increased in opcparse.js. Change MAX_LEDS to a higher value.

**Comment by NickBolles** [comment]
I see that. But is there any other limitation? Or is this just an arbitrary value?

**Comment by bbx10** [comment]
The more LEDs in the string, the more times it takes to update the string. The ws281x data rate is 800,000 bits/second and each LED requires 24 bits (8 bits each for Red, Green, and Blue). Updating 1024 LEDs takes about 31 millisecondss. In other words, 1024 LEDs can be updated about 30 times/sec which is a common rate for animation/video. 2048 LEDs can be updated about 15 times/sec and so on. If you do not need fast updates, the string can very long.

**Comment by NickBolles** [comment]
Awesome! Exactly what I was looking for! 
1024 LEDs is a ton too, so hopefully that's enough. I'm looking into using this library for a project in the future, looks good!
